<?xml version="1.0" ?>
<robot name="archie_mw" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- PROPERTIES -->
  <xacro:include filename="$(find archie_simulation)/robots/archie_mw/xacros/properties.xacro" />
  
  <!-- MATERIALS -->
  <xacro:include filename="$(find archie_simulation)/robots/archie_mw/xacros/materials.xacro" />
  
  <!-- INERTIAL CALCULATIONS -->
  <xacro:include filename="$(find archie_simulation)/robots/archie_mw/xacros/inertial_calc_macros.xacro" />  

  <!--GAZEBO REFERENCES -->
  <!-- <xacro:include filename="$(find archie_simulation)/robots/archie_mw/xacros/archie_mw_gazebo.xacro" /> -->

  <!-- BODY -->
  <xacro:include filename="$(find archie_simulation)/robots/archie_mw/xacros/archie_mw_body.xacro" />
 
  <!-- WHEELS -->
  <!-- <xacro:include filename="$(find archie_simulation)/robots/archie_mw/xacros/mecanum_wheel.xacro" /> -->
  <xacro:include filename="$(find archie_simulation)/robots/archie_mw/xacros/omni_wheel.xacro" />

  <!-- SENSORS --> 
  <!-- <xacro:include filename="$(find archie_simulation)/robots/archie_mw/xacros/sick_S300.xacro" /> -->

  <!-- Microscan - Comment/Uncomment if required -->
  <!-- <xacro:include filename="$(find archie_simulation)/robots/archie_mw/xacros/micro_scan.xacro" />  -->

  <!--Ultrasonics, cameras and IMU's  -->
  <!-->
  <xacro:include filename="$(find archie_simulation)/robots/archie_mw/xacros/imu.xacro" />
  <xacro:include filename="$(find archie_simulation)/robots/archie_mw/xacros/ultrasonic.xacro" />
  <-->
  <!-- <xacro:include filename="$(find archie_simulation)/robots/archie_mw/xacros/camera.xacro" />  -->
  
  <link name="base_link" />

  <!-- Base link macro -->
  <xacro:archie_mw_base name="base_footprint" parent="base_link" lenght="${chassis_lenght}" 
    width="${chassis_width}" height="${chassis_height}" mass="${chassis_weight}" 
    color="Yellow" z_offset="${chassis_center_to_base_footprint_z_offset}">
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:archie_mw_base>

  <!-- Wheel Macro -->
  <!-- <xacro:omni_wheel_250 name="archie_mw_mecanum_wheel_front_left" parent="base_footprint" mass="${wheel_weight}" color="Light_grey"> -->
  <xacro:omni_wheel_250 name="archie_mw_mecanum_wheel_front_left" parent="base_link" >
    <origin xyz="0.25 0.28 0.13" rpy="0 0 0" />
  </xacro:omni_wheel_250>

<!-- 
  <xacro:omni_wheel_250 name="archie_mw_omni_wheel_front_right" parent="base_footprint">
    <origin xyz="0.25 -0.28 0.13" rpy="0 0 3.14" />
  </xacro:omni_wheel_250>

  <xacro:omni_wheel_250 name="archie_mw_omni_wheel_back_left" parent="base_footprint">
    <origin xyz="-0.25 0.28 0.13" rpy="0 0 0" />
  </xacro:omni_wheel_250>

  <xacro:omni_wheel_250 name="archie_mw_omni_wheel_back_right" parent="base_footprint">
    <origin xyz="-0.25 -0.28 0.13" rpy="0 0 3.14" />
  </xacro:omni_wheel_250> -->

  <!-- Sensors -->
  <!-- <xacro:sick_laser_v0 name="lidar_1" parent="base_link" ros_topic="lidar_1/scan_filtered">
    <origin xyz="0.442 0 0.372" rpy="0 0 0" />
  </xacro:sick_laser_v0>

  <xacro:sick_laser_v0 name="lidar_2" parent="base_link" ros_topic="lidar_2/scan_filtered">
    <origin xyz="-0.442 0 0.372" rpy="0 0 3.14" />
  </xacro:sick_laser_v0> -->

  <!--+++++++++++++++++++ IMU ++++++++++++++++++++++++-->
  <!-- Comment or uncomment based on your requirement -->
  <!-->
  <xacro:imu name="imu" parent="base_link">
    <origin xyz="0.100 0 0.300" rpy="0 0 3.14" />
  </xacro:imu>
  <-->

  <!--+++++++++++++++++++ Ultra Sonic ++++++++++++++++++++++++-->
  <!-- Comment or uncomment based on your requirement -->
  <!-- SENSOR 1 --> 
  <!-->
  <xacro:us_sensor name="us_1" parent="base_link">
    <origin xyz="0.100 0 0.500" rpy="0 3.14 3.14" />
  </xacro:us_sensor>
  <-->
  <!-- SENSOR 2 --> 
  <!-- xacro:us_sensor name="us_2" parent="base_link">
    <origin xyz="0.110 0 0.300" rpy="0 3.14 3.14" />
  </xacro:us_sensor-->
  <!-- SENSOR 3 --> 
  <!-- xacro:us_sensor name="us_3" parent="base_link">
    <origin xyz="0.120 0 0.300" rpy="0 3.14 3.14" />
  </xacro:us_sensor-->
  <!-- SENSOR 4 --> 
  <!-- xacro:us_sensor name="us_4" parent="base_link">
    <origin xyz="0.130 0 0.300" rpy="0 3.14 3.14" />
  </xacro:us_sensor-->
  <!-- SENSOR 5 --> 
  <!-- xacro:us_sensor name="us_5" parent="base_link">
    <origin xyz="0.140 0 0.300" rpy="0 3.14 3.14" />
  </xacro:us_sensor-->
  <!-- SENSOR 6 --> 
  <!-- xacro:us_sensor name="us_6" parent="base_link">
    <origin xyz="0.150 0 0.300" rpy="0 3.14 3.14" />
  </xacro:us_sensor-->
  <!-- SENSOR 7 --> 
  <!-- xacro:us_sensor name="us_7" parent="base_link">
    <origin xyz="0.160 0 0.300" rpy="0 3.14 3.14" />
  </xacro:us_sensor-->
  <!-- SENSOR 8 --> 
  <!-- xacro:us_sensor name="us_8" parent="base_link">
    <origin xyz="0.170 0 0.300" rpy="0 3.14 3.14" />
  </xacro:us_sensor-->
  <!-- SENSOR 9 --> 
  <!-- xacro:us_sensor name="us_9" parent="base_link">
    <origin xyz="0.180 0 0.300" rpy="0 3.14 3.14" />
  </xacro:us_sensor-->
  <!-- SENSOR 10 --> 
  <!-- xacro:us_sensor name="us_10" parent="base_link">
    <origin xyz="0.100 0 0.300" rpy="0 3.14 3.14" />
  </xacro:us_sensor-->
  <!-- SENSOR 11 --> 
  <!-- xacro:us_sensor name="us_11" parent="base_link">
    <origin xyz="0.100 0 0.300" rpy="0 3.14 3.14" />
  </xacro:us_sensor-->
  <!-- SENSOR 12 --> 
  <!-- xacro:us_sensor name="us_12" parent="base_link">
    <origin xyz="0.190 0 0.300" rpy="0 3.14 3.14" />
  </xacro:us_sensor-->
  <!-- SENSOR 13 --> 
  <!-- xacro:us_sensor name="us_13" parent="base_link">
    <origin xyz="0.200 0 0.300" rpy="0 3.14 3.14" />
  </xacro:us_sensor-->
  <!-- SENSOR 14 --> 
  <!-- xacro:us_sensor name="us_14" parent="base_link">
    <origin xyz="0.210 0 0.300" rpy="0 3.14 3.14" />
  </xacro:us_sensor-->
  <!-- SENSOR 15 --> 
  <!-- xacro:us_sensor name="us_15" parent="base_link">
    <origin xyz="0.220 0 0.300" rpy="0 3.14 3.14" />
  </xacro:us_sensor-->
  <!-- SENSOR 16 --> 
  <!-- xacro:us_sensor name="us_16" parent="base_link">
    <origin xyz="0.230 0 0.300" rpy="0 3.14 3.14" />
  </xacro:us_sensor-->
    
  <!--Camera  -->
  <!-- <xacro:camera name="camera" parent="base_link">
    <origin xyz="0 0 0.38" rpy="0 0 0" />
  </xacro:camera> -->
<!-- 
  <transmission name="archie_mw_omni_wheel_front_left">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="archie_mw_omni_wheel_front_left_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="archie_mw_omni_wheel_front_left_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="archie_mw_omni_wheel_front_right">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="archie_mw_omni_wheel_front_right_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="archie_mw_omni_wheel_front_right_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="archie_mw_omni_wheel_back_left">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="archie_mw_omni_wheel_back_left_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="archie_mw_omni_wheel_back_left_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="archie_mw_omni_wheel_back_right">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="archie_mw_omni_wheel_back_right_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="archie_mw_omni_wheel_back_right_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission> -->


<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
    <!-- ####### GENERIC CONSTANTS ##### -->

    <!--All units in m-kg-s-radians unit system -->

    <xacro:property name="PI" value="3.1415" />
    <xacro:property name="M_PI" value="3.14159265358979323846264338327950288419716" />
    <!--<xacro:property name="M_PI" value="3.1415926535897931" />-->
    <xacro:property name="ROTATE_90_DEGREES" value="1.570796327" /> <!--pi/2-->
    <xacro:property name="ROTATE_180_DEGREES" value="3.1415926535" /> <!--pi-->
    <xacro:property name="DEG_to_RAD" value="0.017453293" />
    <xacro:property name="SCALE_in_to_m" value="0.0254"/> <!--inches to meters-->
    <xacro:property name="SCALE_mm_to_m" value="0.001"/> <!--milimeters to meters-->
    <xacro:property name="kgcm_to_nm" value="0.0980665" />
    <xacro:property name="gram_to_kg" value="0.001" />


    <!-- ####### "OFF THE SHELVE" ROBOT CHASSIS DIMENSIONS ##### -->

    <!-- ORIGINAL CHASSIS DIMENSIONS  --> 
    <xacro:property name="chassis_lenght" value="${675*SCALE_mm_to_m}" />
    <xacro:property name="chassis_width" value="${530*SCALE_mm_to_m}" />
    <xacro:property name="chassis_height" value="${89*SCALE_mm_to_m}" />
    <xacro:property name="chassis_half_height" value="${chassis_height/2}" />  <!-- 34.5 *SCALE_mm_to_m-->
    <xacro:property name="chassis_weight" value="${19.0-4*0.7}" /> <!-- in kg-->
    <!-- Chassis: distance from the ground to bottom -->
    <xacro:property name="chassis_bottom_z_offset" value="${40.2*SCALE_mm_to_m}" /> 
    <xacro:property name="chassis_center_to_base_footprint_z_offset" value="${40.2*SCALE_mm_to_m + chassis_half_height}" /> 

    
    <!-- EUROPEAN STANDARD 2020 ALUMINIUM EXTRUSION PROFILE DIMENSIONS  --> 
    <xacro:property name="profile_2020_width" value="${20*SCALE_mm_to_m}" />
    <xacro:property name="profile_2020_height" value="${20*SCALE_mm_to_m}" />
    <!-- 2020 1 Meter weights 0.55 kg/m --> <!-- CHECK THE WIGHT FOR THE ACTUAL 2020 PROFILE USED -->
    <xacro:property name="profile_2020_weight_per_mm_lenght" value="${0.55/1000}" /> <!-- in kg/mm-->

    <!-- EUROPEAN STANDARD 2060 ALUMINIUM EXTRUSION PROFILE DIMENSIONS  --> 
    <xacro:property name="profile_2060_width_horizontal" value="${60*SCALE_mm_to_m}" />
    <xacro:property name="profile_2060_height_horizontal" value="${20*SCALE_mm_to_m}" />
    <xacro:property name="profile_2060_width_vertical" value="${20*SCALE_mm_to_m}" />
    <xacro:property name="profile_2060_height_vertical" value="${60*SCALE_mm_to_m}" />
  <!-- 2060 1 Meter wights 1.21 kg/m --> <!-- CHECK THE WIGHT FOR THE ACTUAL 2060 PROFILE USED -->
    <xacro:property name="profile_2060_weight_per_mm_lenght" value="${1.21/1000}" /> <!-- in kg/mm-->

    <!-- MOTOR WITH SUPPORT AND ELASTIC CLUTCH COUPLER DIMENSIONS  -->
    <!--  2.16 Kg - approximate with a box: h: 69 w: 60 l: 71+133.5+19 =223.5-->
    <xacro:property name="motor_assy_width" value="${60*SCALE_mm_to_m}" />
    <xacro:property name="motor_assy_height" value="${69*SCALE_mm_to_m}" />
    <xacro:property name="motor_assy_lenght" value="${223.5*SCALE_mm_to_m}" />


    <!-- FLANGE / WHEEL HINGE -->
    <!--  0.06 Kg - approximate with cylinder d56.8 h26.4+5=31.4 -->
    <xacro:property name="wheel_flange_diameter" value="${56.8*SCALE_mm_to_m}" />
    <xacro:property name="wheel_flange_lenght" value="${31.4*SCALE_mm_to_m}" />

    <!-- MECANUM WHEEL  SHAFT-->
    <xacro:property name="shaft_diameter" value="${30.0*SCALE_mm_to_m}" />
    <xacro:property name="shaft_radius" value="${shaft_diameter/2}" />
    <!-- <xacro:property name="shaft_lenght" value="${23*SCALE_mm_to_m}" /> -->
    <xacro:property name="shaft_lenght" value="${23.0*SCALE_mm_to_m}" />
    <xacro:property name="shaft_half_lenght" value="${shaft_lenght/2}" />
    <xacro:property name="shaft_mass" value="0.06" /> <!-- in kg-->
    <xacro:property name="shaft_x_offset" value="${307.5*SCALE_mm_to_m}" />
    <xacro:property name="shaft_y_offset" value="${265*SCALE_mm_to_m}" />
    <xacro:property name="shaft_z_offset" value="${34.5*SCALE_mm_to_m}" />

    <!-- MECANUM WHEELS -->
    <xacro:property name="wheel_diameter" value="${6*SCALE_in_to_m}" />
    <xacro:property name="wheel_radius" value="${wheel_diameter/2}" />
    <xacro:property name="wheel_width" value="${46*SCALE_mm_to_m}" />
    <xacro:property name="wheel_weight" value="0.820" /> <!--  in kg - TODO: CHECK THE NUMBER AGAIN /> -->

    <xacro:property name="left_wheel_x_offset" value="${307.5*SCALE_mm_to_m}" />
    <xacro:property name="left_wheel_y_offset" value="${288.645468*SCALE_mm_to_m}" />
    <xacro:property name="left_wheel_z_offset" value="${34.5*SCALE_mm_to_m}" />


<!-- ####### END ROBOT PARTS DIMENSIONS AND CONSTANTS ##### -->

<!--###################################################################################-->
<!--###################################################################################-->  

<!-- ####### SENSORS ##### -->

  <!-- RPLIDAR A2  -->
  <xacro:property name="rplidar_diameter" value="${0.0757}" />
  <xacro:property name="rplidar_height_of_laser_beam_plane" value="${0.0308}" />
  <xacro:property name="rplidar_height" value="${0.0408}" />
  <!-- <xacro:property name="rplidar_X_offset" value="${round_plate_radius-rplidar_diameter/2-0.01}" />
  <xacro:property name="rplidar_Y_offset" value="${0.0}" />
  <xacro:property name="rplidar_Z_offset" value="${round_plate_height+rplidar_height_of_laser_beam_plane}" />
  <xacro:property name="rplidar_mesh_X_offset" value="${0.0}" />
  <xacro:property name="rplidar_mesh_Y_offset" value="${-rplidar_diameter/2 + 0.007}" />
  <xacro:property name="rplidar_mesh_Z_offset" value="${-rplidar_height_of_laser_beam_plane}" /> -->
  

    <!-- CAMERA -->
  <xacro:property name="cameraSize" value="${0.05}"/>
  <xacro:property name="cameraMass" value="${0.1}"/>

<!--###################################################################################-->
    <material name="_Light_black">
        <color rgba="0.15 0.15 0.15 1.0" />
    </material>
    <material name="Black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>
    <material name="Blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
    </material>
    <material name="Green">
        <color rgba="0.0 0.8 0.0 1.0"/>
    </material>
    <material name="Light_grey">
      <color rgba="0.4 0.4 0.4 1.0" />
    </material>
    <material name="Grey">
        <color rgba="0.2 0.2 0.2 1.0"/>
    </material>
    <material name="DarkGrey">
        <color rgba="0.1 0.1 0.1 1.0"/>
    </material>
    <material name="Yellow">
        <color rgba="0.8 0.8 0.0 1.0" />
    </material>
    <material name="Orange">
        <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
    </material>
    <material name="Brown">
        <color rgba="${222/255} ${207/255} ${195/255} 1.0"/>
    </material>
    <material name="Red">
        <color rgba="0.8 0.0 0.0 1.0"/>
    </material>
    <material name="White">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>

<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->  
</robot>
